In [13]:
import torch

# used to create the empty array and the array is uninitialised
x=torch.empty(3) 
print(x)

#2d array
x=torch.empty(2,3)
print(x)

#Array with random values
x=torch.rand(3)
print(x)

#Array with intial zeros values
x=torch.zeros(2,2) 
print(x)

#Array with ones values
x=torch.ones(2,2)
print(x)

#printing the datatype of the array
print(x.dtype)

#creating array with other datatypes
x=torch.ones(2,2,dtype=torch.int)
x=torch.zeros(2,2,dtype=torch.double)

#Size
print(x.size())

#creating tensor/array from initial list
x=torch.tensor([1,2,3,4])
print(x)



tensor([-1.0161e+18,  4.5612e-41,  1.2485e+33])
tensor([[1.2475e+33, 3.0890e-41, 9.2626e+30],
        [3.0890e-41, 1.2437e+33, 3.0890e-41]])
tensor([0.8287, 0.8719, 0.8903])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
torch.float32
torch.Size([2, 2])
tensor([1, 2, 3, 4])


In [24]:
#Arithematic operations
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)

#element wise addition
z=x+y
print(z)

#inplace addition operation: in this we dont store addition result in new array but in same array 
#y values will be changed below 
y.add_(x)
print(y)

# similarty for add,multiplication and division

#Slicing operation:
#print all rows 0th column
print(x[:,0])

#print(1 row all columns)
print(x[0,:])

#print(complete tensor)
print(x[:,:])

#print element at 1st row 1st column
print(x[1,1])

#to above method is printing tensor suppose we need the value only
print(x[1,1].item())

tensor([[0.5530, 0.2229],
        [0.6849, 0.5502]])
tensor([[0.7540, 0.9926],
        [0.4971, 0.7260]])
tensor([[1.3070, 1.2156],
        [1.1820, 1.2762]])
tensor([[1.3070, 1.2156],
        [1.1820, 1.2762]])
tensor([0.5530, 0.6849])
tensor([0.5530, 0.2229])
tensor([[0.5530, 0.2229],
        [0.6849, 0.5502]])
tensor(0.5502)
0.5501731634140015


In [29]:
#converting the numpy array to torch array and vice versa
import numpy as np

#converting the pytorch array to numpy array both array points to same memory location means if we change one
#array changes will also reflect in other
a=torch.ones(5)
print(a)
b=a.numpy()
print(b)

#converting the numpy array to the torch array,the both array points to same memory location here also
a=np.ones(5)
print(a)
b=torch.from_numpy(a)
print(b)



tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
